hrr26-berets/hrr26-berets

package.json
1. removed the stray comma.
2. added react-router-dom per the note [here](https://www.npmjs.com/package/react-router)
=> fixed package.json error and added dependency

db/models/user.js, server/server.js
we were using the wrong syntax for bodyParser in server.js
also cleaned up user.js
=> fixed bodyParser syntax in server.js

db/models/user.js, server/request-handler.js
we will use email address as username instead.
=> deleted e-mail field from user model

src/client/app/Main.jsx, src/client/app/ProductDetails.jsx, src/client/app/ShoppingList.jsx, src/client/app/index.jsx, src/client/app/item.jsx, src/client/app/popularItems.jsx
made small changes in most components to properly render and import/export
=> init commit for main page and component import

public/index.html, src/client/app/Main.jsx
also added bootstrap.min.css to index.html
=> added thumbnail image to mock data, 

src/client/app/Item.jsx, src/client/app/PopularItems.jsx
quick edit to render the popular items horizontally on the main page
=> popular items now render horizontally

src/client/app/Main.jsx, src/client/app/SearchBar.jsx
=> (feat) Hooked up Main and SearchBar to backend API call.

server/request-handler.js, src/client/app/SearchBar.jsx
=> Edited req-handler to accept custom search params

src/client/app/PopularItems.jsx, src/client/app/PopularItems.test.js
=> Added basic tests for PopularItems, component still renders w/out props

package.json, public/style.css, server/request-handler.js, server/server.js, src/client/app/FeaturedLists.jsx, src/client/app/Login.jsx, src/client/app/Main.jsx, src/client/app/ProductDetails.jsx, src/client/app/SearchBar.jsx, src/client/app/SearchResults.jsx, src/client/app/SearchResultsEntry.jsx, src/client/app/Signup.jsx
search now returns a list of five results.
clicking on the item name will open up product details (still WIP).
=> Search results

public/style.css, server/request-handler.js, src/client/app/SearchResults.jsx, src/client/app/SearchResultsEntry.jsx
^What the page looks like with search result styles.
Changes in this pull request:
Added 2 lines in exports.search in req-handler to grab product thumbnail and url for our returned data.
Added images and urls to SearchresultsEntry component.
Added url as href, target="_blank" to each entry to open link to Walmart product entry in a new tab.
Spaced out the entries and made the buttons look more like buttons.
=> Added images, urls, styling to search results.

src/client/app/Main.jsx, src/client/app/SearchResultsEntry.jsx
=> removed all href='#'

src/client/app/ProductDetails.jsx, src/client/app/SearchResultsEntry.jsx
Just pass down itemId and itemUrl to ProductDetails and it will take care of the rest.
=> refactored productDetails to independently handle get request

package.json, server/request-handler.js, src/client/app/ProductDetails.jsx
- refactored lookup handler to consistently fetch the proper long description.
- added new dependency (request-promise)
=> refactored lookup handler

server/request-handler.js, server/server.js, src/client/app/Item.jsx, src/client/app/Main.jsx, src/client/app/PopularItems.jsx
small commit as a placeholder
now on todo list for popular items:
- invoke product details view onclick
- add add to list and buy it now buttons
=> popular items now renders first five of Walmart's trending items

src/client/app/Main.jsx, src/client/app/SearchResults.jsx, src/client/app/SearchResultsEntry.jsx
^^example console logs of currentList state changes when clicking the Add To List button for various items
In this pull request:
Added currentList array to state in Main
Created handleAddToList function in Main to add new items to currentList
Passed handleAddToList down to SearchResultsEntry
Created click handler in SearchResultsEntry to grab the correct item to call addToList with
=> Added ability to save list items to currentList in Main state.

src/client/app/Item.jsx, src/client/app/Main.jsx, src/client/app/PopularItems.jsx
changed the variable name from product to item to keep it consistent with search results.
=> added product details modal and add & buy buttons to popular items

server/request-handler.js, src/client/app/Main.jsx, src/client/app/ShoppingList.jsx
^^log of the data returned from a successful list save.  Only saves one list at a time right now because they're all called 'Untitled' 
In this pull request:
Wrote save function in Main that creates an object in the format {listname: [...listItems]} and makes a POST request to the /save endpoint with that object as the req body.
Added Save button to ShoppingList component that calls save function on click
Edited backend storeProduct function to avoid sending a separate response to the client side for each product (was causing a bug with the headers).
Edited save_shopping function to grab shopping list from req.body instead of req.body.shoppingList
=> (feat) hooked Save button up to backend save function.

src/client/app/FeaturedItem.jsx, src/client/app/FeaturedLists.jsx, src/client/app/Main.jsx
so that ProductDetails invoked from Featured Item works properly.
=> passing addToList to Featured Lists

src/client/app/Item.jsx, src/client/app/Item.test.js, src/client/app/ListItem.test.js, src/client/app/PopularItems.test.js, src/client/app/ProductDetails.test.js, src/client/app/SearchBar.test.js, src/client/app/SearchResults.test.js, src/client/app/SearchResultsEntry.jsx, src/client/app/SearchResultsEntry.test.js
updated:
- Item.test.js
- PopularItems.test.js
created:
- ListItem.test.js
- ProductDetails.test.js
- SearchBar.test.js
- SearchResults.test.js
- SearchResultsEntry.test.js
All tests passing as of this pull request.
=> updated & created unit tests

db/config.js, public/index.html, public/style.css, server/server.js, src/client/app/FeaturedItem.jsx, src/client/app/Item.jsx, src/client/app/Login.jsx, src/client/app/Main.jsx, src/client/app/ProductDetails.jsx, src/client/app/SearchBar.jsx, src/client/app/SearchResultsEntry.jsx, src/client/app/Signup.jsx
and a quick fix for the duplicate bug
=> overall sweep to make code more deployment friendly 

public/style.css, src/client/app/Main.jsx, src/client/app/SearchResultsEntry.jsx, src/client/app/ShoppingList.jsx
In this pull request:
-nameChange function that sets this.state.currentListName in Main to an inputted name
-Passed down nameChange to ShoppingList
-Added text input field and name-change button to ShoppingList
-Wired up value of text input field to ShoppingList state
-Edited styling of ShoppingList name-change and save buttons so they fit on one line and don't run into anything
=> (feat) adds ability to change user shopping list name

src/client/app/SearchBar.jsx
not sure when/how this came back, but got rid of it again.
=> got rid of localhost in SearchBar.jsx

src/client/app/App.jsx, src/client/app/Main.jsx
Temporarily commented out the two FeaturedList functions while we sort out the rate limit issue.
=> Moved logout function to App, passed to Main.

package.json, src/client/app/Main.jsx, src/client/app/ShoppingListEntry.jsx
Conditionally renders ShoppingList based on whether a user is logged in
Asks user to log in if a user tries to add an item to a list without being logged in, prevents the rest of addToList() from running.
Added react-select, style-loader, css-loader to package json
=> Login conditionals updated w/latest changes

.eslintrc.js, db/config.js, db/models/product.js, package.json, server/api-requests.js, server/request-handler.js, server/server.js, src/client/app/App.jsx, src/client/app/FeaturedItem.jsx, src/client/app/FeaturedLists.jsx, src/client/app/Item.jsx, src/client/app/Item.test.js, src/client/app/ListItem.jsx, src/client/app/ListItem.test.js, src/client/app/Login.jsx, src/client/app/Main.jsx, src/client/app/PopularItems.jsx, src/client/app/PopularItems.test.js, src/client/app/ProductDetails.jsx, src/client/app/ProductDetails.test.js, src/client/app/SearchBar.jsx, src/client/app/SearchBar.test.js, src/client/app/SearchResults.jsx, src/client/app/SearchResults.test.js, src/client/app/SearchResultsEntry.jsx, src/client/app/SearchResultsEntry.test.js, src/client/app/ShoppingList.jsx, src/client/app/ShoppingListEntry.jsx, src/client/app/Signup.jsx, src/client/app/index.jsx
Sorry sorry there are like 30 files in the pull because I linted them.
=> Installed linter, linted all the files

src/client/app/Main.jsx
Fixed a stray direct state modification in getFeaturedList
Refactored jsx conditionals in render to be clearer and more modular
Added comments indicating what each section of our rendered components was supposed to do.
=> Finished refactoring Main.

public/style.css, src/client/app/FeaturedLists.jsx, src/client/app/Item.jsx, src/client/app/ListItem.jsx, src/client/app/Login.jsx, src/client/app/Main.jsx, src/client/app/PopularItems.jsx, src/client/app/ProductDetails.jsx, src/client/app/Signup.jsx
- cleaned up empty spaces (some were triggering false results on the unit tests)
- got rid of unnecessary console.logs
- fixed use of "var"
- added min width to popular item and bottom-aligned them. the trade off is that they no longer automatically collapse, but we should be fine up to a width of 640px.
=> code cleanup

public/style.css, src/client/app/ListItem.jsx, src/client/app/PopularItems.jsx
- align popular items text to center
- pass addToList to ProductDetails from ListItem
- add text-link class to product name to get cursor: pointer
- add btn-block class to popular items buttons to make width uniform
- add is-table-row class to popular items for vertical alignment
- changed variable name to match param for isInList
=> bug fix for product details / addToList

public/style.css, src/client/app/ListItem.jsx, src/client/app/Main.jsx
=> Styling, added box around popular items

.gitignore, server/request-handler.js, server/server.js, src/client/app/Main.jsx, src/client/app/ShoppingList.jsx, src/client/app/ShoppingListEntry.jsx
- Added cancel button to rename list
- Working implementation of removeList backend/frontend. Still needs more polish (i.e. switching to another list upon current list's removal)
=> shopping list ui/ux changes

package.json, server/request-handler.js, src/client/app/Main.jsx
added redis to package.json for the "new" featuredList as well.
=> re-implemented fixed featured list and removed unnecessary console logs

package.json, server/request-handler.js
updated package.json with mongoose version compatible with MLabs
updated mongoose request handlers with syntax that is compatible with mongoose v4
=> mongoose fix
